create own fork of the password saml library and make it a npm pacakge to consume
Foxquilt/foxden-node-saml pull request #1
Opened 2023-01-10 15:19 UTC by suriyaka

Jira:
https://foxquilt.atlassian.net/browse/ARCH-32

Description:

Created foxden node_saml npm package

2023-01-10 16:07 UTC, joeydeeth approved these changes

2023-01-10 16:08 UTC, FoxquiltChris commented on .circleci/config.yml
> +version: 2.1
Build will need to be similar to one of our repos that are being published to NPM. (E.g. shared library, Foxden Tools, Version Controller client, etc.)

2023-01-10 16:09 UTC, FoxquiltChris commented on .npmrc
> +//registry.npmjs.org/:_authToken=${NPM_TOKEN}
You'll probably also want an .npmignore file to make sure we're not bundling files that we shouldn't be.

2023-01-10 16:11 UTC, FoxquiltChris commented on package.json
> +    "deploy:staging": "sls deploy --stage stage",
Don't change any of their scripts. We didn't write this project so our build tooling won't work on this repo.

2023-01-10 16:11 UTC, FoxquiltChris commented on package.json
> +    "yarn": "^1.22.19"
No need to add yarn as a dependency.

2023-01-10 16:11 UTC, FoxquiltChris commented on package.json
> +  "version": "4.0.4",
Version number doesn't matter since we're technically creating a "new" package. You can set this to 1.0.0.

2023-01-10 16:16 UTC, FoxquiltChris requested changes
A few things... you're maybe overthinking this a bit! 😉 
- No need to convert this project to Yarn
- This package was written using different build tools than what we use. That's fine! No need to change that! Don't modify anything in the `scripts` section of the package.json.
- The CircleCI config file should be adapted from one of our repos that are published to NPM. (Since that's what we're going to be doing with this one!)

2023-01-10 18:30 UTC, joeydeeth approved these changes

2023-01-10 18:47 UTC, Eric-G-Ji commented on src/xml.ts
> +  return true;
Why does this always return true, even when the `checkSignature` call returns false?

2023-01-10 18:53 UTC, Eric-G-Ji commented on src/xml.ts
> +    return true;
Why does it still return true when more than one referenced nodes exist?

2023-01-10 21:54 UTC, FoxquiltChris commented on package.json
> +  "name": "@foxden/node-saml",
Other than the `name` and `repository` fields, we should generally leave this file alone - especially, the `license` section. MIT license is pretty open.

2023-01-10 21:54 UTC, FoxquiltChris approved these changes
Tentatively approved. Pls address Eric's comments and consider rolling back unnecessary changes to package.json file.

2023-01-10 22:21 UTC, suriyaka commented
> 
Reverted package json and added only the name and repository .updated an comment on eric's review comments.

2023-01-10 23:00 UTC, merged

2023-01-11 21:44 UTC, srd90 commented
Just in case @ mentions didn't work (notifications were not sent) because mentioned github users were not active at PR where those @ mentions were done see these comments:
1. https://github.com/node-saml/node-saml/pull/245#issuecomment-1379475764
2. https://github.com/node-saml/node-saml/pull/245#issuecomment-1379506204
   * especially re-enabling few tests

@FoxquiltChris @Eric-G-Ji @joeydeeth